### ISSUE TITLE
More json data be prefered, since GSX blocked enrolled_count. 

### ISSUE THREAD

**Issue by cjwang666** [67647f8/gsx-fraud#3]
Only one json data is not enough to analyze deeper.

**Comment by 67647f8** [comment]
Uploaded everything to the data folder.
All files are in JSON format, timestamped on when we downloaded the data.
The inception timestamp is May 9, this is the one we use in the report. The timestamp is in PDT, since the job was running on an AWS server in US west coast.

Gaotu masked enrolled_count to 0 around Jun 2 PDT. The last few files has enrolled count = 0.
